# Generated by Django 4.2.7 on 2026-03-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nai_security", "0004_securitysettings_axes_attempt_expiry_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whitelisteduser",
            name="exemption_type",
            field=models.CharField(
                choices=[
                    ("rate_limit", "Rate Limiting Only"),
                    ("ip_block", "IP Blocking Only"),
                    ("geo_block", "Country/Geo Blocking Only"),
                    ("all", "All Security Checks"),
                ],
                default="all",
                help_text="Type of security check to bypass",
                max_length=20,
            ),
        ),
    ]
